config/routes.rb
Rails.application.routes.draw do
  # get 'favorites/show'
  # get 'favorites/edit'
  # get 'favorites/update'
  # get 'favorites/new'
  # get 'products/index'
  # get 'products/show'
  # get 'users/index'
  # get 'users/new'
  # get 'users/create'
  # get 'users/show'
  # get 'users/edit'
  # get 'users/update'
  # get 'users/destroy'
  # get 'welcome/index'
  
   delete "/reviews/:id", to: "reviews#destroy", as: "delete_review"
   patch "/reviews/:id",  to: "reviews#update", as: "edit_review"
  resources :favorites, only: [:show, :edit, :update, :new] 
  resources :reviews
  resources :products
  resources :users

  resource :sessions, only: [:new, :create]

  #Show and Edit Profile
# get '/profile', to: 'users#profile', as: 'profile'
  
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :products
    belongs_to :users
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :reviews
  has_many :users, through: :reviews

 # has_many :favorites
  #has_many :users, through: :favorites
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
    has_many :reviews
    has_many :products, through: :reviews

    #has_many :favorites
    #has_many :products, through: :favorites

    include BCrypt

    def password
      @password ||= Password.new(password_hash)
    end
  
    def password=(new_password)
      @password = Password.create(new_password)
      self.password_hash = @password
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def show

  end

  def edit
  end

  def update
  end

  def new
  @favorite = Favorite.new
  end

  def destroy
    @favorite.destroy
    respond_to do |format|
      format.html { redirect_to favorites_url, notice: 'Favorite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_favorite
    @favorite = Favorite.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def favorite_params
    params.require(:favorite).permit(:user_id, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user
  
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @review = Review.new
    @users = User.all
  end

  private 
  

  def authenticate_user
    if session[:current_user] == nil 
      redirect_to new_sessions_path, notice: "Please login to continue"
    end
  end

end

#button to favorite

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_review, only: [:show, :edit, :update, :destroy]

    def index
        @reviews = Review.all
    end
    
    def show
      @users = User.all
    end

    def edit
      @review = Review.find_by(id: params[:id])
    end

    def new
        @review = Review.new
    end

    def create
      product_id = request.referrer.split("/").last.to_i
     
      user_id = session[:current_user]["id"].to_i
      content = params[:review][:content]
      rating = params[:review][:rating]
     
        @review = Review.new(
          product_id: product_id,
          user_id: user_id,
          content: content,
          rating: rating
        )
        respond_to do |format|
        
          if @review.valid?
            @review.save
            
            format.html { redirect_to product_path(product_id), notice: 'Review was successfully created.' }
            format.json { render :show, status: :created, location: @user }
          else
            format.html { redirect_to product_path(product_id) }
            format.json { render json: @review.errors, status: :unprocessable_entity }
          end
        end
    end

      def update
        product_id = request.referrer.split("/").last.to_i
        user_id = session[:current_user]["id"].to_i
        content = params[:review][:content]
        rating = params[:review][:rating]

        review = Review.find(params[:id])
        product_id = review.product.id

        @review = Review.update(
          content: content,
          rating: rating
        ).first
        
       redirect_to product_path(@review.product_id)

      # call review instance update      find, update, and redirect product_path(pid)
      # @review.product_id
      # @review = Review.find_by(id: params[:id])
      # redirect_to product_path(product_id)
      # @review = Review.find(params[:id])
      end

      def destroy
        review = Review.find(params[:id])
        product_id = review.product.id
        review.destroy
        respond_to do |format|
          format.html { redirect_to product_path(product_id), notice: 'Review was successfully destroyed.' }
          # format.html { redirect_back(fallback_location: products_path), notice: 'Review was successfully destroyed.' }
          # redirect_back(fallback_location: products_path)
          format.json { head :no_content }
        end
      end









    private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:content, :rating, :user_id, :product_id, :text)
    end
end

    

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by_username(login_params[:username])
    if @user && @user.password == login_params[:password]
      session[:current_user] = @user

      redirect_to products_path, notice: "Hello #{@user.username}!"
    else
      redirect_to root_path, notice: "Invalid username or password"
    end
  end

  private 

  def login_params
    params.require(:login).permit(:username, :password)      
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(username: user_params[:username])
    @user.password = user_params[:password]
  
    if @user.valid?
      @user.save

      session[:current_user] = @user

      redirect_to @user
    else
      redirect_to user_path
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def logout
    session[:current_user] = nil
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    #@user.destroy

    # Destroy user session
    session[:current_user] = nil 

    respond_to do |format|
      format.html { redirect_to root_path, notice: "You have been signed out!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def search
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/favorites/edit.html.erb
<h1>Favorites#edit</h1>
<p>Find me in app/views/favorites/edit.html.erb</p>

app/views/favorites/new.html.erb
<h1>Favorites#new</h1>
<p>Find me in app/views/favorites/new.html.erb</p>

app/views/favorites/show.html.erb
<h1>Favorites#show</h1>
<p>Find me in app/views/favorites/show.html.erb</p>

app/views/favorites/update.html.erb
<h1>Favorites#update</h1>
<p>Find me in app/views/favorites/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloom</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>



    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
     <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

   <body>
<div>

</div>
  


<div style="margin-right: 10px">
 <% if session[:current_user] %>
    <%= link_to "Logout", user_path(session[:current_user]["id"]), method: :delete, data: { confirm: "Are you sure?" } %>  | <%= session[:current_user]["username"] %>
<% else %>
   <%= link_to "Login", new_sessions_path %>
 <% end %>
</div>

<%= notice %>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>Plants</h1>
<hr>
<% @products.each do |p|%>
<br>
<br>

<br>

    <%= link_to p.name, product_path(p)%> 
     
<% end %>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>
<br>
<em><%= @product.scientific_name%></em>
<hr>
<br>
<p><%= @product.fun_fact%></p>
<% @plant_image = @product.name.gsub(/\s+/, "") + ".jpg" %>
<% if @plant_image %>
 <%= image_tag("productimages/#{@plant_image}") %>
 <%end%>

<br>
<br>
<%= form_for @review do |form| %>
<p>
 <%#= collection_select(:user, :id, @users, :id, :username) %>
<br>
<br>
   <%= form.label :How_bossy_is_she_? %>
    <%= form.number_field :rating %>
 
  <p>  <br>    
              .:Love Tips:.
    <%= form.label :How_do_you_care_for_her? %>
    <%= form.text_area :content %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>



<% @product.reviews.each do |r| %>
     <p><%= r.content%></p>
     <%=button_to "Delete Review", delete_review_path(r.id), :method => :delete, :class=> "btn btn-primary btn-sm" %>
     <%= link_to "<button>Edit Review</button>".html_safe, edit_review_path(r.id), :class=> "btn btn-secondary btn-sm" %>
     <%end%>

 

app/views/reviews/edit.html.erb
<h1>Edit Your Review</h1>

<%= form_for @review do |form| %>
<p>
 <%= collection_select(:user, :id, @users, :id, :username) %>
<br>
<br>
   <%= form.label :How_would_you_rate_this_plant? %><br>
    <%= form.number_field :rating %>
 
  <p>
    <%= form.label :Any_care_tips? %><br>
    <%= form.text_area :content %>
  </p>
 
  <p>
    <%= form.submit "Edit" %>
  </p>
<% end %>

app/views/reviews/new.html.erb
<h1>New Review</h1>


<%= form_with scope: :review, url:reviews_path, local: true do |form| %>
  <p>
    <%= form.label :Product %><br>
    <%= form.text_field :title %>
  </p>

   <%= form.label :rating %><br>
    <%= form.number_field :rating %>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/reviews/show.html.erb
<h1>Edit Your Review</h1>

<%= form_for @review do |form| %>
<p>
 <%= collection_select(:user, :id, @users, :id, :username) %>
<br>
<br>
   <%= form.label :How_would_you_rate_this_plant? %><br>
    <%= form.number_field :rating %>
 
  <p>
    <%= form.label :Any_care_tips? %><br>
    <%= form.text_area :content %>
  </p>
 
  <p>
    <%= form.submit "Edit" %>
  </p>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>

    <%= form.text_field :username %>

  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>
<%= link_to 'Back', users_path %>


<%= form_with model: User.new, class: "" do |f| %>
   <%= f.label :Username %>
   <%= f.text_field :username %>
     <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

   <%= f.submit "Create" %>
<% end %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @user.username %></h1>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/welcome/index.html.erb
<h1>Bloom</h1>
<br>
<p> A community for plant lovers.</p>